language: java
dist: trusty
jdk:
  - openjdk11

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

addons:
  chrome: stable
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: "m6YtJXyy+gZR1HBrK+kMI8yueXztQ3l0A4aaIO3p+VUviVIsPzYVCuTkZvXdOUpI/w54QKI5wuLdCBeHtfcUWCWrAEfT2DNkz68ENZakiS4Mu4LesQe/d2aWKpzIqPkibp68flnccY9whgX/uYayHha93nuN1j9XmjSKRInj+NSZhzVwZb3DNH6eq1YF+Pz0yVQHvOUoE1Dd8KF1kYBPUMzxVQSpOi0CiwLydBNUK3b4QT4wf5wMLYjELU3Ljl8YqbN4sTMCiR4FGstnOS3fmwe1rCjcmqfof6XO5ro2n+1JKQLdHVMbH6aEFnr21nAsebArDeVSDwGTsaSFg8Vt14HeSW8evWpG+XEINQT9wO9klRXe4cIvN4rUNUNeWVA9h+tjzfVwANVu/byW6qejrqKyiP4tHpepD9gsVTAUiAL0QqH+qudxWLzNBz5uDksdMmexhX/usAxeS51kZDC9xIX1XmzhJiQnPW3gdWkw3guBVYUj9Vby5z1Xz80rimUIr+dGuTqa/2cwjjtkZUpuJdpc6OrTmvmMNIVkWNuyjvifSuVZYZcd6DiRj1cwBtBuo1v07rF0rP5s+TduGze8IMMv08fh1qX6n6oTsFyob8HkVC2T0W9bDVUy08dbK0M+VC47le5HQd+CvZTPW4es45uddRa+6NUBRNvze171RP4="
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

deploy:
  - provider: script
    script: mvn dockerfile:push
    on:
      branch: development

env:
  global:
    - secure: "M8xXgZ8lbKr/DHKe0N/SSVBBHvQzbCyMlJ871Bqb7FvmnWEFcm5LH4GHGRYtyVRbwesAMPd+4mMFsJx+QB2tfZorMylKUmPSBTmrvLXy5AfwHa71VTVeXQAq0XNV2MmBVDULRD1kUfCAGhFZYOAJ7oSmF37Sz/5pG0lredwyzGm6rhdnh3bWR9QcJZfhXyNS/AIkE87fgEuRTPka6OhvlrFvjIH6pb0+/8FJ/Inz5eq+GNoZauQUXnl78rNF8p48JHAxzFg/VTO+30X/yGTLRbglC1Dv+SRA4ob0Fkl3qqOiJy6mrpeWY7LuwgRJICzlox35snotMJQih1GpG4Fpm52Dt6FRF/dFAoUxbWd5VFUyvsAzqqcFuaxho48C7KvpolUZqvJJ25yKpBxfKlHtSKwaSBsFrg3H0u1CnH8DgkJHKC0yLszhgRuM09lHNg6u4ShXiMamSCbJO5AtFjSh5XVQtzMhbGOiaTkk5gC8vGuoxds6lJdF5nDmy7zvugaFGRyoETGJNjUFX4e9pIj7LCpwoJ8iBxdPRBsP4u1qYRekJCgpqKt7pAuXpzkAvPv7rEOieW+ddF6pCeX+sq5zyzRw2n6XXm7dyALB9RzDryS4ZTlsVgDkI29xeRzvFgYNu1ydk/gD1qj4L8C4zwlVZNJwfCcddWeoIjVt8hFL7v4="
    # ^^ DOCKER_USERNAME
    - secure: "BRAxiewXbIiYe2EaVQjFAmE7z+Hmi354UURJ/csOFO0xeNe+O2eSSXtPs8L8t7stnHcxTkUaR045Rcm+flMsloaND85Km1zALU5Hx5mhV7sjKV8zuzPWVFbDjielw/FxI662IEy/jXSqeLO5qYvt5R6346GUQ2yP2RDUT99XivOvM6lQLRFhPElBLgfdS+LPe9GvvA/+RJgHVwS9cmnIzDN5cJRzoeehJNf36cEA7CwZ1/f+LNU47EqNugEM79HLUtWCFKv9VUec4NZDyB1xp0lOQunHXwezoXPgVnOfmmnVmvZldFCSOuv8W1LlqyFJNnw8SRXHIXCQ3Ywvl91KC6dqJURVLdS3ejJYAjssbnNUnpLVwIQPqN1RzLAOdAdMehkea3W4Ntr1AhZGrBKyGnfcDkZk+IbmMGRDCYIMhFR404q1HgzRTQYvXm3d3VRRChirBqzwggi4y6CtQmBdJkguUU302Wu05qoLASAy1E2V/E2ArXIJfvirUT9dm2lK5uk4fdHc71GrNWxjjLAMyAzZRPV0jyUn+amlVsNUQfDR8iAqEPqv7XvQPxZnKAD4X8YhLgsHtX9tjqzbYkl/oIgwFyLj7AqMfQN1EZuvOk3euEaHzyTbi6QFeF2JOzhpWXEqj/kTEI6w9rjMoKl+kj62MptC2IGu8Z2EbRh/jhc="
    # ^^ DOCKER_PASSWORD

before_script:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.2,10}/main/pg_hba.conf
  - sudo service postgresql restart
  - psql -c "CREATE DATABASE authorization_server_integration;" -U postgres
  - psql -c "CREATE USER authorization_server_integration_user WITH PASSWORD 'authorization_server_integration_user_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE authorization_server_integration TO authorization_server_integration_user;" -U postgres
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - mvn clean install dockerfile:build sonar:sonar -Pprod

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
